import { Station, FuelRecord, ImportSession, GeneratorBrand, GeneratorModel } from './types';

export const generatorBrands: GeneratorBrand[] = [
  { id: 'b1', name: 'Cummins',    country: 'Mỹ',      active: true,  note: 'Thương hiệu phổ biến nhất' },
  { id: 'b2', name: 'Mitsubishi', country: 'Nhật Bản', active: true,  note: '' },
  { id: 'b3', name: 'Denyo',      country: 'Nhật Bản', active: true,  note: 'Chuyên máy phát công suất nhỏ-vừa' },
  { id: 'b4', name: 'Perkins',    country: 'Anh',      active: true,  note: '' },
  { id: 'b5', name: 'Honda',      country: 'Nhật Bản', active: true,  note: 'Chủ yếu công suất nhỏ' },
  { id: 'b6', name: 'Doosan',     country: 'Hàn Quốc', active: false, note: 'Ngưng nhập về' },
];

export const generatorModels: GeneratorModel[] = [
  { id: 'm1',  brandId: 'b1', brandName: 'Cummins',    modelName: 'C100D5',   powerKva: 100, fuelType: 'diesel',   suggestedRate: 10, suggestedCapacity: 200, active: true,  note: '3 pha' },
  { id: 'm2',  brandId: 'b1', brandName: 'Cummins',    modelName: 'C200D5',   powerKva: 200, fuelType: 'diesel',   suggestedRate: 18, suggestedCapacity: 500, active: true,  note: '3 pha, phổ biến' },
  { id: 'm3',  brandId: 'b1', brandName: 'Cummins',    modelName: 'C50D5',    powerKva: 50,  fuelType: 'diesel',   suggestedRate: 6,  suggestedCapacity: 150, active: true,  note: '' },
  { id: 'm4',  brandId: 'b2', brandName: 'Mitsubishi', modelName: 'MGS250B',  powerKva: 250, fuelType: 'diesel',   suggestedRate: 22, suggestedCapacity: 600, active: true,  note: 'Công suất lớn' },
  { id: 'm5',  brandId: 'b2', brandName: 'Mitsubishi', modelName: 'MGS100B',  powerKva: 100, fuelType: 'diesel',   suggestedRate: 10, suggestedCapacity: 250, active: true,  note: '' },
  { id: 'm6',  brandId: 'b3', brandName: 'Denyo',      modelName: 'DCA-25',   powerKva: 25,  fuelType: 'diesel',   suggestedRate: 3,  suggestedCapacity: 80,  active: true,  note: 'Nhỏ gọn' },
  { id: 'm7',  brandId: 'b3', brandName: 'Denyo',      modelName: 'DCA-60',   powerKva: 60,  fuelType: 'diesel',   suggestedRate: 7,  suggestedCapacity: 150, active: true,  note: '' },
  { id: 'm8',  brandId: 'b4', brandName: 'Perkins',    modelName: '1104A-44', powerKva: 75,  fuelType: 'diesel',   suggestedRate: 7,  suggestedCapacity: 150, active: true,  note: '' },
  { id: 'm9',  brandId: 'b5', brandName: 'Honda',      modelName: 'EU15i',    powerKva: 15,  fuelType: 'gasoline', suggestedRate: 1.2,suggestedCapacity: 30,  active: true,  note: 'Xăng' },
  { id: 'm10', brandId: 'b6', brandName: 'Doosan',     modelName: 'P500E',    powerKva: 500, fuelType: 'diesel',   suggestedRate: 38, suggestedCapacity: 900, active: false, note: 'Ngưng sử dụng' },
];

export const stations: Station[] = [
  { id: 's1',  code: 'ST001', name: 'Trạm Hà Nội 1',       generatorName: 'Cummins HN-01', address: '15 Phố Huế, Hoàn Kiếm, Hà Nội',               adminUnit: 'Q. Hoàn Kiếm, Hà Nội',   oldTerritory: 'HN-A1', managementZone: 'Khu vực Bắc 1', lat: 21.028, lng: 105.851, brandId: 'b1', brandName: 'Cummins',    modelId: 'm1',  modelName: 'C100D5',   powerKva: 100, fuelType: 'diesel', fuelRate: 10, maxCapacity: 200,  currentFuel: 45,  lastUpdated: '2026-06-12', updatedToday: true,  active: true },
  { id: 's2',  code: 'ST002', name: 'Trạm Hà Nội 2',       generatorName: 'Cummins HN-02', address: '88 Láng Hạ, Đống Đa, Hà Nội',                  adminUnit: 'Q. Đống Đa, Hà Nội',     oldTerritory: 'HN-A2', managementZone: 'Khu vực Bắc 1', lat: 21.019, lng: 105.831, brandId: 'b1', brandName: 'Cummins',    modelId: 'm2',  modelName: 'C200D5',   powerKva: 200, fuelType: 'diesel', fuelRate: 18, maxCapacity: 500,  currentFuel: 12,  lastUpdated: '2026-06-12', updatedToday: true,  active: true },
  { id: 's3',  code: 'ST003', name: 'Trạm Hải Phòng 1',    generatorName: 'HP-Gen-01',     address: '45 Điện Biên Phủ, Lê Chân, Hải Phòng',         adminUnit: 'Q. Lê Chân, Hải Phòng',  oldTerritory: 'HP-01', managementZone: 'Khu vực Bắc 2', lat: 20.858, lng: 106.684, brandId: 'b4', brandName: 'Perkins',    modelId: 'm8',  modelName: '1104A-44', powerKva: 75,  fuelType: 'diesel', fuelRate: 7,  maxCapacity: 150,  currentFuel: 8,   lastUpdated: '2026-06-11', updatedToday: false, active: true },
  { id: 's4',  code: 'ST004', name: 'Trạm Quảng Ninh',     generatorName: 'QN-Gen-01',     address: '12 Trần Phú, Hạ Long, Quảng Ninh',             adminUnit: 'TP. Hạ Long, Quảng Ninh', oldTerritory: 'QN-01', managementZone: 'Khu vực Bắc 2', lat: 20.951, lng: 107.073, brandId: 'b1', brandName: 'Cummins',    modelId: 'm1',  modelName: 'C100D5',   powerKva: 100, fuelType: 'diesel', fuelRate: 10, maxCapacity: 200,  currentFuel: null,lastUpdated: null,         updatedToday: false, active: true },
  { id: 's5',  code: 'ST005', name: 'Trạm Đà Nẵng 1',      generatorName: 'DN-Cum-01',     address: '23 Nguyễn Văn Linh, Hải Châu, Đà Nẵng',       adminUnit: 'Q. Hải Châu, Đà Nẵng',   oldTerritory: 'DN-01', managementZone: 'Khu vực Trung 1',lat: 16.068, lng: 108.212, brandId: 'b1', brandName: 'Cummins',    modelId: 'm2',  modelName: 'C200D5',   powerKva: 200, fuelType: 'diesel', fuelRate: 18, maxCapacity: 500,  currentFuel: 35,  lastUpdated: '2026-06-12', updatedToday: true,  active: true },
  { id: 's6',  code: 'ST006', name: 'Trạm Đà Nẵng 2',      generatorName: 'DN-Den-01',     address: '67 Nguyễn Tất Thành, Sơn Trà, Đà Nẵng',       adminUnit: 'Q. Sơn Trà, Đà Nẵng',    oldTerritory: 'DN-02', managementZone: 'Khu vực Trung 1',lat: 16.089, lng: 108.231, brandId: 'b3', brandName: 'Denyo',      modelId: 'm7',  modelName: 'DCA-60',   powerKva: 60,  fuelType: 'diesel', fuelRate: 7,  maxCapacity: 150,  currentFuel: 5,   lastUpdated: '2026-06-10', updatedToday: false, active: true },
  { id: 's7',  code: 'ST007', name: 'Trạm Huế',             generatorName: 'Hue-Cum-01',    address: '34 Lý Thường Kiệt, TP Huế, TT-Huế',           adminUnit: 'TP. Huế, T-T Huế',       oldTerritory: 'HUE-01',managementZone: 'Khu vực Trung 1',lat: 16.467, lng: 107.591, brandId: 'b1', brandName: 'Cummins',    modelId: 'm1',  modelName: 'C100D5',   powerKva: 100, fuelType: 'diesel', fuelRate: 10, maxCapacity: 200,  currentFuel: 18,  lastUpdated: '2026-06-11', updatedToday: false, active: true },
  { id: 's8',  code: 'ST008', name: 'Trạm Quy Nhơn',        generatorName: 'QN-Gen-01',     address: '78 Nguyễn Huệ, TP Quy Nhơn, Bình Định',       adminUnit: 'TP. Quy Nhơn, Bình Định', oldTerritory: 'QNH-01',managementZone: 'Khu vực Trung 2',lat: 13.783, lng: 109.219, brandId: 'b1', brandName: 'Cummins',    modelId: 'm1',  modelName: 'C100D5',   powerKva: 100, fuelType: 'diesel', fuelRate: 10, maxCapacity: 200,  currentFuel: 3,   lastUpdated: '2026-06-09', updatedToday: false, active: true },
  { id: 's9',  code: 'ST009', name: 'Trạm Nha Trang 1',     generatorName: 'NT-Per-01',     address: '99 Trần Phú, Vĩnh Nguyên, Nha Trang',         adminUnit: 'TP. Nha Trang, Khánh Hòa',oldTerritory: 'NT-01', managementZone: 'Khu vực Trung 2',lat: 12.238, lng: 109.197, brandId: 'b4', brandName: 'Perkins',    modelId: 'm8',  modelName: '1104A-44', powerKva: 75,  fuelType: 'diesel', fuelRate: 7,  maxCapacity: 150,  currentFuel: 60,  lastUpdated: '2026-06-12', updatedToday: true,  active: true },
  { id: 's10', code: 'ST010', name: 'Trạm Nha Trang 2',     generatorName: 'NT-Den-01',     address: '56 Lê Lợi, Phước Tiến, Nha Trang',            adminUnit: 'TP. Nha Trang, Khánh Hòa',oldTerritory: 'NT-02', managementZone: 'Khu vực Trung 2',lat: 12.247, lng: 109.183, brandId: 'b3', brandName: 'Denyo',      modelId: 'm6',  modelName: 'DCA-25',   powerKva: 25,  fuelType: 'diesel', fuelRate: 3,  maxCapacity: 80,   currentFuel: null,lastUpdated: null,         updatedToday: false, active: true },
  { id: 's11', code: 'ST011', name: 'Trạm TP.HCM 1',        generatorName: 'HCM-Mits-01',  address: '120 Nguyễn Thị Minh Khai, Quận 1, TP.HCM',   adminUnit: 'Q. 1, TP.HCM',           oldTerritory: 'HCM-A1',managementZone: 'Khu vực Nam 1', lat: 10.784, lng: 106.700, brandId: 'b2', brandName: 'Mitsubishi', modelId: 'm4',  modelName: 'MGS250B',  powerKva: 250, fuelType: 'diesel', fuelRate: 22, maxCapacity: 600,  currentFuel: 150, lastUpdated: '2026-06-12', updatedToday: true,  active: true },
  { id: 's12', code: 'ST012', name: 'Trạm TP.HCM 2',        generatorName: 'HCM-Cum-01',   address: '45 Võ Văn Tần, Quận 3, TP.HCM',              adminUnit: 'Q. 3, TP.HCM',           oldTerritory: 'HCM-A2',managementZone: 'Khu vực Nam 1', lat: 10.775, lng: 106.692, brandId: 'b1', brandName: 'Cummins',    modelId: 'm2',  modelName: 'C200D5',   powerKva: 200, fuelType: 'diesel', fuelRate: 18, maxCapacity: 500,  currentFuel: 25,  lastUpdated: '2026-06-12', updatedToday: true,  active: true },
  { id: 's13', code: 'ST013', name: 'Trạm TP.HCM 3',        generatorName: 'HCM-Cum-02',   address: '234 Xô Viết Nghệ Tĩnh, Bình Thạnh, TP.HCM',  adminUnit: 'Q. Bình Thạnh, TP.HCM',  oldTerritory: 'HCM-B1',managementZone: 'Khu vực Nam 1', lat: 10.803, lng: 106.706, brandId: 'b1', brandName: 'Cummins',    modelId: 'm1',  modelName: 'C100D5',   powerKva: 100, fuelType: 'diesel', fuelRate: 10, maxCapacity: 200,  currentFuel: 9,   lastUpdated: '2026-06-11', updatedToday: false, active: true },
  { id: 's14', code: 'ST014', name: 'Trạm Biên Hòa',         generatorName: 'BH-Cum-01',    address: '67 CM Tháng 8, Biên Hòa, Đồng Nai',          adminUnit: 'TP. Biên Hòa, Đồng Nai', oldTerritory: 'BH-01', managementZone: 'Khu vực Nam 2', lat: 10.943, lng: 106.824, brandId: 'b1', brandName: 'Cummins',    modelId: 'm2',  modelName: 'C200D5',   powerKva: 200, fuelType: 'diesel', fuelRate: 18, maxCapacity: 500,  currentFuel: 40,  lastUpdated: '2026-06-12', updatedToday: true,  active: true },
  { id: 's15', code: 'ST015', name: 'Trạm Vũng Tàu',         generatorName: 'VT-Per-01',    address: '89 Lê Lợi, TP Vũng Tàu, BR-VT',             adminUnit: 'TP. Vũng Tàu, BR-VT',    oldTerritory: 'VT-01', managementZone: 'Khu vực Nam 2', lat: 10.346, lng: 107.086, brandId: 'b4', brandName: 'Perkins',    modelId: 'm8',  modelName: '1104A-44', powerKva: 75,  fuelType: 'diesel', fuelRate: 7,  maxCapacity: 150,  currentFuel: null,lastUpdated: null,         updatedToday: false, active: true },
  { id: 's16', code: 'ST016', name: 'Trạm Cần Thơ 1',        generatorName: 'CT-Cum-01',    address: '12 Hòa Bình, Ninh Kiều, Cần Thơ',            adminUnit: 'Q. Ninh Kiều, Cần Thơ',  oldTerritory: 'CT-01', managementZone: 'Khu vực Nam 3', lat: 10.044, lng: 105.747, brandId: 'b1', brandName: 'Cummins',    modelId: 'm1',  modelName: 'C100D5',   powerKva: 100, fuelType: 'diesel', fuelRate: 10, maxCapacity: 200,  currentFuel: 7,   lastUpdated: '2026-06-11', updatedToday: false, active: true },
  { id: 's17', code: 'ST017', name: 'Trạm Cần Thơ 2',        generatorName: 'CT-Den-01',    address: '45 Nguyễn Văn Cừ, Bình Thủy, Cần Thơ',       adminUnit: 'Q. Bình Thủy, Cần Thơ',  oldTerritory: 'CT-02', managementZone: 'Khu vực Nam 3', lat: 10.056, lng: 105.763, brandId: 'b3', brandName: 'Denyo',      modelId: 'm7',  modelName: 'DCA-60',   powerKva: 60,  fuelType: 'diesel', fuelRate: 7,  maxCapacity: 150,  currentFuel: 28,  lastUpdated: '2026-06-12', updatedToday: true,  active: true },
  { id: 's18', code: 'ST018', name: 'Trạm An Giang',          generatorName: 'AG-Cum-01',    address: '23 Tôn Đức Thắng, Long Xuyên, An Giang',     adminUnit: 'TP. Long Xuyên, An Giang',oldTerritory: 'AG-01', managementZone: 'Khu vực Nam 3', lat: 10.386, lng: 105.435, brandId: 'b1', brandName: 'Cummins',    modelId: 'm1',  modelName: 'C100D5',   powerKva: 100, fuelType: 'diesel', fuelRate: 10, maxCapacity: 200,  currentFuel: 15,  lastUpdated: '2026-06-10', updatedToday: false, active: true },
  { id: 's19', code: 'ST019', name: 'Trạm Kiên Giang',        generatorName: 'KG-Cum-01',    address: '67 Rạch Sỏi, Rạch Giá, Kiên Giang',         adminUnit: 'TP. Rạch Giá, Kiên Giang',oldTerritory: 'KG-01', managementZone: 'Khu vực Nam 3', lat: 10.012, lng: 105.080, brandId: 'b1', brandName: 'Cummins',    modelId: 'm3',  modelName: 'C50D5',    powerKva: 50,  fuelType: 'diesel', fuelRate: 6,  maxCapacity: 150,  currentFuel: 4,   lastUpdated: '2026-06-09', updatedToday: false, active: true },
  { id: 's20', code: 'ST020', name: 'Trạm Cà Mau',            generatorName: 'CM-Den-01',    address: '34 Lý Bôn, TP Cà Mau, Cà Mau',              adminUnit: 'TP. Cà Mau, Cà Mau',     oldTerritory: 'CM-01', managementZone: 'Khu vực Nam 3', lat: 9.186,  lng: 105.150, brandId: 'b3', brandName: 'Denyo',      modelId: 'm6',  modelName: 'DCA-25',   powerKva: 25,  fuelType: 'diesel', fuelRate: 3,  maxCapacity: 80,   currentFuel: 22,  lastUpdated: '2026-06-11', updatedToday: false, active: true },
  { id: 's21', code: 'ST021', name: 'Trạm Vinh',              generatorName: 'Vinh-Cum-01',  address: '89 Nguyễn Văn Cừ, TP Vinh, Nghệ An',        adminUnit: 'TP. Vinh, Nghệ An',      oldTerritory: 'NA-01', managementZone: 'Khu vực Bắc 3', lat: 18.680, lng: 105.681, brandId: 'b1', brandName: 'Cummins',    modelId: 'm2',  modelName: 'C200D5',   powerKva: 200, fuelType: 'diesel', fuelRate: 18, maxCapacity: 500,  currentFuel: 85,  lastUpdated: '2026-06-12', updatedToday: true,  active: true },
  { id: 's22', code: 'ST022', name: 'Trạm Thanh Hóa',         generatorName: 'TH-Cum-01',    address: '12 Đại lộ Lê Lợi, TP Thanh Hóa',            adminUnit: 'TP. Thanh Hóa, Thanh Hóa',oldTerritory: 'TH-01', managementZone: 'Khu vực Bắc 3', lat: 19.807, lng: 105.776, brandId: 'b1', brandName: 'Cummins',    modelId: 'm1',  modelName: 'C100D5',   powerKva: 100, fuelType: 'diesel', fuelRate: 10, maxCapacity: 200,  currentFuel: 30,  lastUpdated: '2026-06-11', updatedToday: false, active: true },
  { id: 's23', code: 'ST023', name: 'Trạm Nam Định',          generatorName: 'ND-Mits-01',   address: '56 Cô Bắc, TP Nam Định',                     adminUnit: 'TP. Nam Định, Nam Định',  oldTerritory: 'ND-01', managementZone: 'Khu vực Bắc 1', lat: 20.421, lng: 106.177, brandId: 'b2', brandName: 'Mitsubishi', modelId: 'm5',  modelName: 'MGS100B',  powerKva: 100, fuelType: 'diesel', fuelRate: 10, maxCapacity: 250,  currentFuel: null,lastUpdated: null,         updatedToday: false, active: true },
  { id: 's24', code: 'ST024', name: 'Trạm Thái Nguyên',       generatorName: 'TN-Per-01',    address: '23 Hoàng Văn Thụ, TP Thái Nguyên',          adminUnit: 'TP. Thái Nguyên',         oldTerritory: 'TNG-01',managementZone: 'Khu vực Bắc 2', lat: 21.594, lng: 105.847, brandId: 'b4', brandName: 'Perkins',    modelId: 'm8',  modelName: '1104A-44', powerKva: 75,  fuelType: 'diesel', fuelRate: 7,  maxCapacity: 150,  currentFuel: 55,  lastUpdated: '2026-06-12', updatedToday: true,  active: true },
  { id: 's25', code: 'ST025', name: 'Trạm Lạng Sơn',          generatorName: 'LS-Cum-01',    address: '45 Trần Đăng Ninh, TP Lạng Sơn',            adminUnit: 'TP. Lạng Sơn, Lạng Sơn', oldTerritory: 'LS-01', managementZone: 'Khu vực Bắc 2', lat: 21.853, lng: 106.762, brandId: 'b1', brandName: 'Cummins',    modelId: 'm1',  modelName: 'C100D5',   powerKva: 100, fuelType: 'diesel', fuelRate: 10, maxCapacity: 200,  currentFuel: 6,   lastUpdated: '2026-06-08', updatedToday: false, active: true },
  { id: 's26', code: 'ST026', name: 'Trạm Phú Thọ',           generatorName: 'PT-Den-01',    address: '78 Hùng Vương, TP Việt Trì, Phú Thọ',       adminUnit: 'TP. Việt Trì, Phú Thọ',  oldTerritory: 'PT-01', managementZone: 'Khu vực Bắc 1', lat: 21.323, lng: 105.401, brandId: 'b3', brandName: 'Denyo',      modelId: 'm7',  modelName: 'DCA-60',   powerKva: 60,  fuelType: 'diesel', fuelRate: 7,  maxCapacity: 150,  currentFuel: 33,  lastUpdated: '2026-06-11', updatedToday: false, active: true },
  { id: 's27', code: 'ST027', name: 'Trạm Pleiku',            generatorName: 'PLK-Per-01',   address: '34 Nguyễn Văn Trỗi, TP Pleiku, Gia Lai',    adminUnit: 'TP. Pleiku, Gia Lai',     oldTerritory: 'GL-01', managementZone: 'Khu vực Trung 2',lat: 13.983, lng: 108.002, brandId: 'b4', brandName: 'Perkins',    modelId: 'm8',  modelName: '1104A-44', powerKva: 75,  fuelType: 'diesel', fuelRate: 7,  maxCapacity: 150,  currentFuel: 11,  lastUpdated: '2026-06-10', updatedToday: false, active: true },
  { id: 's28', code: 'ST028', name: 'Trạm Buôn Ma Thuột',     generatorName: 'BMT-Cum-01',   address: '67 Điện Biên Phủ, TP BMT, Đắk Lắk',        adminUnit: 'TP. Buôn Ma Thuột',      oldTerritory: 'DL-01', managementZone: 'Khu vực Trung 2',lat: 12.668, lng: 108.038, brandId: 'b1', brandName: 'Cummins',    modelId: 'm2',  modelName: 'C200D5',   powerKva: 200, fuelType: 'diesel', fuelRate: 18, maxCapacity: 500,  currentFuel: 70,  lastUpdated: '2026-06-12', updatedToday: true,  active: true },
  { id: 's29', code: 'ST029', name: 'Trạm Đà Lạt',            generatorName: 'DL-Den-01',    address: '12 Trần Phú, TP Đà Lạt, Lâm Đồng',         adminUnit: 'TP. Đà Lạt, Lâm Đồng',  oldTerritory: 'LD-01', managementZone: 'Khu vực Trung 2',lat: 11.940, lng: 108.442, brandId: 'b3', brandName: 'Denyo',      modelId: 'm6',  modelName: 'DCA-25',   powerKva: 25,  fuelType: 'diesel', fuelRate: 3,  maxCapacity: 80,   currentFuel: 19,  lastUpdated: '2026-06-11', updatedToday: false, active: true },
  { id: 's30', code: 'ST030', name: 'Trạm Long An',           generatorName: 'LA-Cum-01',    address: '89 Nguyễn Thị Minh Khai, TP Tân An, Long An',adminUnit: 'TP. Tân An, Long An',    oldTerritory: 'LA-01', managementZone: 'Khu vực Nam 2', lat: 10.530, lng: 106.415, brandId: 'b1', brandName: 'Cummins',    modelId: 'm1',  modelName: 'C100D5',   powerKva: 100, fuelType: 'diesel', fuelRate: 10, maxCapacity: 200,  currentFuel: 2,   lastUpdated: '2026-06-07', updatedToday: false, active: true },
  // Trạm chưa có tọa độ
  { id: 's31', code: 'ST031', name: 'Trạm Bạc Liêu',          generatorName: 'BL-Den-01',    address: '23 Trần Phú, TP Bạc Liêu, Bạc Liêu',       adminUnit: 'TP. Bạc Liêu, Bạc Liêu', oldTerritory: 'BL-01', managementZone: 'Khu vực Nam 3', lat: null,   lng: null,   brandId: 'b3', brandName: 'Denyo',      modelId: 'm6',  modelName: 'DCA-25',   powerKva: 25,  fuelType: 'diesel', fuelRate: 3,  maxCapacity: 80,   currentFuel: 18,  lastUpdated: '2026-06-10', updatedToday: false, active: true },
  { id: 's32', code: 'ST032', name: 'Trạm Sóc Trăng',         generatorName: 'ST-Cum-01',    address: '45 Lê Lợi, TP Sóc Trăng, Sóc Trăng',       adminUnit: 'TP. Sóc Trăng, Sóc Trăng',oldTerritory: 'STG-01',managementZone: 'Khu vực Nam 3', lat: null,   lng: null,   brandId: 'b1', brandName: 'Cummins',    modelId: 'm1',  modelName: 'C100D5',   powerKva: 100, fuelType: 'diesel', fuelRate: 10, maxCapacity: 200,  currentFuel: null,lastUpdated: null,         updatedToday: false, active: true },
];

export const fuelRecords: FuelRecord[] = [
  { id: 'fr1',  stationId: 's1',  date: '2026-06-12', previousFuel: 38, added: 20, hoursRun: 12, consumed: 12, endFuel: 46,  difference: 0,  source: 'import',  note: 'Import định kỳ tháng 6' },
  { id: 'fr2',  stationId: 's1',  date: '2026-06-11', previousFuel: 50, added: 0,  hoursRun: 12, consumed: 12, endFuel: 38,  difference: 0,  source: 'manual' },
  { id: 'fr3',  stationId: 's1',  date: '2026-06-10', previousFuel: 62, added: 0,  hoursRun: 12, consumed: 12, endFuel: 50,  difference: 0,  source: 'manual' },
  { id: 'fr4',  stationId: 's2',  date: '2026-06-12', previousFuel: 20, added: 10, hoursRun: 10, consumed: 18, endFuel: 12,  difference: 0,  source: 'import' },
  { id: 'fr5',  stationId: 's5',  date: '2026-06-12', previousFuel: 53, added: 0,  hoursRun: 10, consumed: 18, endFuel: 35,  difference: 0,  source: 'import' },
  { id: 'fr6',  stationId: 's9',  date: '2026-06-12', previousFuel: 74, added: 0,  hoursRun: 10, consumed: 14, endFuel: 60,  difference: 0,  source: 'import' },
  { id: 'fr7',  stationId: 's11', date: '2026-06-12', previousFuel: 172,added: 0,  hoursRun: 10, consumed: 22, endFuel: 150, difference: 0,  source: 'import' },
  { id: 'fr8',  stationId: 's12', date: '2026-06-12', previousFuel: 43, added: 0,  hoursRun: 10, consumed: 18, endFuel: 25,  difference: 0,  source: 'import' },
];

export const importSessions: ImportSession[] = [
  { id: 'imp1', filename: 'nhien_lieu_thang6_w2.xlsx', importedBy: 'Nguyễn Văn A', importedAt: '2026-06-12 08:30', totalRows: 30, validRows: 27, warningRows: 2, errorRows: 1, status: 'committed' },
  { id: 'imp2', filename: 'nhien_lieu_thang6_w1.xlsx', importedBy: 'Trần Thị B',   importedAt: '2026-06-05 09:15', totalRows: 30, validRows: 29, warningRows: 1, errorRows: 0, status: 'committed' },
  { id: 'imp3', filename: 'nhien_lieu_thang5_w4.xlsx', importedBy: 'Lê Văn C',     importedAt: '2026-05-29 10:00', totalRows: 30, validRows: 25, warningRows: 3, errorRows: 2, status: 'committed' },
  { id: 'imp4', filename: 'nhien_lieu_thang5_w3_test.xlsx', importedBy: 'Phạm D',  importedAt: '2026-05-15 14:20', totalRows: 30, validRows: 20, warningRows: 5, errorRows: 5, status: 'failed' },
  { id: 'imp5', filename: 'nhien_lieu_thang5_w3.xlsx', importedBy: 'Phạm D',       importedAt: '2026-05-15 15:00', totalRows: 30, validRows: 28, warningRows: 2, errorRows: 0, status: 'committed' },
];
